Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -37,19 +37,36 @@ jobs:
         
     - name: Update ECS Task Definition
       run: |
-        # Define variables
-        BRANCH_OR_TAG=$(git rev-parse --abbrev-ref HEAD)
-        TASK_DEFINITION_ARN="arn:aws:ecs:us-east-1:475768992472:task-definition/auto-normalize-iz6m29xlzo8a770dbc180028ba90d9b2"
-        NEW_IMAGE="475768992472.dkr.ecr.us-east-1.amazonaws.com/idscience/ecs-auto-normalize:$BRANCH_OR_TAG"
-        # Retrieve the existing task definition
-        aws ecs describe-task-definition \
-            --task-definition "$TASK_DEFINITION_ARN" \
-            --query 'taskDefinition' \
-            --output json > task-def.json
-        # Modify the image URL in the container definition
-        jq --arg new_image "$NEW_IMAGE" '
-        .containerDefinitions[0].image = $new_image |
-        del(.revision, .status, .taskDefinitionArn, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)
-        ' task-def.json > updated-task-def.json
-        # Register the new task definition
-        aws ecs register-task-definition --cli-input-json file://updated-task-def.json
+          set -e
+
+          # Get the current branch or tag
+          BRANCH_OR_TAG=$(git rev-parse --abbrev-ref HEAD)
+          TASK_DEFINITION_ARN="arn:aws:ecs:us-east-1:223449663023:task-definition/auto-normalize"
+          NEW_IMAGE="223449663023.dkr.ecr.us-east-1.amazonaws.com/idscience/ecs-auto-normalize:$BRANCH_OR_TAG"
+
+          echo "Branch or Tag: $BRANCH_OR_TAG"
+          echo "New Image: $NEW_IMAGE"
+
+          # Retrieve the existing task definition
+          if ! aws ecs describe-task-definition \
+              --task-definition "$TASK_DEFINITION_ARN" \
+              --query 'taskDefinition' \
+              --output json > task-def.json; then
+            echo "Failed to retrieve task definition" >&2
+            exit 1
+          fi
+
+          # Modify the image URL in the container definition
+          if ! jq --arg new_image "$NEW_IMAGE" '
+            .containerDefinitions[0].image = $new_image |
+            del(.revision, .status, .taskDefinitionArn, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)
+            ' task-def.json > updated-task-def.json; then
+            echo "Failed to modify task definition" >&2
+            exit 1
+          fi
+
+          # Register the new task definition
+          if ! aws ecs register-task-definition --cli-input-json file://updated-task-def.json; then
+            echo "Failed to register new task definition" >&2
+            exit 1
+          fi
